/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;

export const idlService = IDL.Service({
  'cleanAndFormatContent' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(IDL.Text)],
      [],
    ),
  'generateScript' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], []),
  'getRecentScripts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Time, IDL.Vec(IDL.Text)))],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  
  return IDL.Service({
    'cleanAndFormatContent' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(IDL.Text)],
        [],
      ),
    'generateScript' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], []),
    'getRecentScripts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Time, IDL.Vec(IDL.Text)))],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };